/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/components/atoms/Button`; params?: Router.UnknownInputParams; } | { pathname: `/components/atoms/TimeDisplay`; params?: Router.UnknownInputParams; } | { pathname: `/components/atoms/TextDisplay`; params?: Router.UnknownInputParams; } | { pathname: `/components/molecules/ControlButtonGroup`; params?: Router.UnknownInputParams; } | { pathname: `/components/molecules/PomodoroCounter`; params?: Router.UnknownInputParams; } | { pathname: `/components/molecules/StatusDisplay`; params?: Router.UnknownInputParams; } | { pathname: `/components/organisms/PomodoroTimer`; params?: Router.UnknownInputParams; } | { pathname: `/context/PomodoroContext`; params?: Router.UnknownInputParams; } | { pathname: `/components/templates/PomodoroTemplate`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/ControlButtons`; params?: Router.UnknownInputParams; } | { pathname: `/components/Pomodoro`; params?: Router.UnknownInputParams; } | { pathname: `/components/PomodoroContext`; params?: Router.UnknownInputParams; } | { pathname: `/components/PomodoroCounter`; params?: Router.UnknownInputParams; } | { pathname: `/components/StatusMessage`; params?: Router.UnknownInputParams; } | { pathname: `/components/Timer`; params?: Router.UnknownInputParams; } | { pathname: `/styles/timerStyles`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/components/atoms/Button`; params?: Router.UnknownOutputParams; } | { pathname: `/components/atoms/TimeDisplay`; params?: Router.UnknownOutputParams; } | { pathname: `/components/atoms/TextDisplay`; params?: Router.UnknownOutputParams; } | { pathname: `/components/molecules/ControlButtonGroup`; params?: Router.UnknownOutputParams; } | { pathname: `/components/molecules/PomodoroCounter`; params?: Router.UnknownOutputParams; } | { pathname: `/components/molecules/StatusDisplay`; params?: Router.UnknownOutputParams; } | { pathname: `/components/organisms/PomodoroTimer`; params?: Router.UnknownOutputParams; } | { pathname: `/context/PomodoroContext`; params?: Router.UnknownOutputParams; } | { pathname: `/components/templates/PomodoroTemplate`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/components/ControlButtons`; params?: Router.UnknownOutputParams; } | { pathname: `/components/Pomodoro`; params?: Router.UnknownOutputParams; } | { pathname: `/components/PomodoroContext`; params?: Router.UnknownOutputParams; } | { pathname: `/components/PomodoroCounter`; params?: Router.UnknownOutputParams; } | { pathname: `/components/StatusMessage`; params?: Router.UnknownOutputParams; } | { pathname: `/components/Timer`; params?: Router.UnknownOutputParams; } | { pathname: `/styles/timerStyles`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/components/atoms/Button${`?${string}` | `#${string}` | ''}` | `/components/atoms/TimeDisplay${`?${string}` | `#${string}` | ''}` | `/components/atoms/TextDisplay${`?${string}` | `#${string}` | ''}` | `/components/molecules/ControlButtonGroup${`?${string}` | `#${string}` | ''}` | `/components/molecules/PomodoroCounter${`?${string}` | `#${string}` | ''}` | `/components/molecules/StatusDisplay${`?${string}` | `#${string}` | ''}` | `/components/organisms/PomodoroTimer${`?${string}` | `#${string}` | ''}` | `/context/PomodoroContext${`?${string}` | `#${string}` | ''}` | `/components/templates/PomodoroTemplate${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/components/ControlButtons${`?${string}` | `#${string}` | ''}` | `/components/Pomodoro${`?${string}` | `#${string}` | ''}` | `/components/PomodoroContext${`?${string}` | `#${string}` | ''}` | `/components/PomodoroCounter${`?${string}` | `#${string}` | ''}` | `/components/StatusMessage${`?${string}` | `#${string}` | ''}` | `/components/Timer${`?${string}` | `#${string}` | ''}` | `/styles/timerStyles${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/components/atoms/Button`; params?: Router.UnknownInputParams; } | { pathname: `/components/atoms/TimeDisplay`; params?: Router.UnknownInputParams; } | { pathname: `/components/atoms/TextDisplay`; params?: Router.UnknownInputParams; } | { pathname: `/components/molecules/ControlButtonGroup`; params?: Router.UnknownInputParams; } | { pathname: `/components/molecules/PomodoroCounter`; params?: Router.UnknownInputParams; } | { pathname: `/components/molecules/StatusDisplay`; params?: Router.UnknownInputParams; } | { pathname: `/components/organisms/PomodoroTimer`; params?: Router.UnknownInputParams; } | { pathname: `/context/PomodoroContext`; params?: Router.UnknownInputParams; } | { pathname: `/components/templates/PomodoroTemplate`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/ControlButtons`; params?: Router.UnknownInputParams; } | { pathname: `/components/Pomodoro`; params?: Router.UnknownInputParams; } | { pathname: `/components/PomodoroContext`; params?: Router.UnknownInputParams; } | { pathname: `/components/PomodoroCounter`; params?: Router.UnknownInputParams; } | { pathname: `/components/StatusMessage`; params?: Router.UnknownInputParams; } | { pathname: `/components/Timer`; params?: Router.UnknownInputParams; } | { pathname: `/styles/timerStyles`; params?: Router.UnknownInputParams; };
    }
  }
}
